[package]
name = "tgbot"
version = "0.1.0"
authors = ["dracarys18 <karthihegde010@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version="0.5",features = ["auto-send", "macros"] }
log = "0.4.8"
pretty_env_logger = "0.4.0"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros","time"] }
tokio-stream = "0.1.6"
mongodb = "2.0.0-beta.2"
anyhow = "*"
lazy_static = "*"
async_once = "*"
dotenv = "*"
reqwest = {version="*",features= ["json"]}
serde = {version = "*",features = ["derive"]}
serde_json = "*"
regex = "*"
mime = "*"
chrono = "0.4"